# For development & testing with sender-backend

version: '3.9'

services:
  sender-frontend:
    platform: linux/arm/v7
    container_name: sender-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: "base" # select dockerfile stage to use
    image: "ghcr.io/upri-earthquake/sender-frontend:dev"
    volumes:
      # bind local dir to reflect changes in container
      # NOTE: includes everything, including all those in .dockerignore, specifically .env
      - ./:/app
    ports:  # expose nginx ports to host
      - "3000:3000"
    command: npm start
