# For development & testing with sender-backend

version: '3.9'

services:
  sender-frontend:
    platform: linux/arm64/v8
    container_name: sender-frontend
    image: "ghcr.io/upri-earthquake/sender-frontend:0.0.2"
    depends_on:
      - "sender-backend"
    environment:
      - NGINX_PORT=80
    ports:  # expose nginx ports to host
      - "3000:3000"
    networks:
      app-network:
        ipv4_address: 172.24.0.2

  sender-backend:
    platform: linux/arm64/v8
    container_name: sender-backend
    image: "ghcr.io/upri-earthquake/sender-backend:0.0.3"
    expose:
      - "5001"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.24.0.3

networks:
  app-network:
    name: sender-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
