# Stage 1: base, minimal setup for dev, shall contain non-js deps.
#          To be bind-mounted to local dev files (includint node_modules)
FROM arm32v7/node:18-alpine as base

EXPOSE 3000

WORKDIR /app